### ISSUE TITLE
jdk21 spring3.2debug无法正常启动，17则正常

### ISSUE THREAD

**Issue by xiejilan** [newhoo/bean-invoker#11]
21无法正常启动
![image](https://github.com/user-attachments/assets/9bf2e5b8-7373-4293-b10e-8488700c39cc)
17可以正常启动
![image](https://github.com/user-attachments/assets/44561b86-b475-420f-9d3c-1bde72556ac9)

**Comment by newhoo** [comment]
![图片](https://github.com/user-attachments/assets/897afc14-ce8f-467c-997e-739dc721f3a0)
正常启动，可以在设置中关闭插件再启动看看吧

**Comment by xiejilan** [comment]
可能是旗舰版有上面的问题，我又下载了社区版用17和21均可以debug模式启动
