### ISSUE TITLE
不能maven package了

### ISSUE THREAD

**Issue by ghost** [newhoo/bean-invoker#3]
I cannot run maven if bean-invoker is enabled,
my jetbrains' version is 231.8770.65 but bean-invoker find the location of 223.8617.56.plugins which doesn't exist anymore
**D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56.plugins\bean-invoker-intellij-plugin\lib\bean-invoker-agent-1.0.2-with-dependencies.jar**

the error is below:
C:\Users\01388303\.jdks\corretto-1.8.0_362\bin\java.exe -Dvisualvm.id=16096521313500 -Dvisualgc.id=16096012378200 -Dmaven.multiModuleProjectDirectory=E:\projects\isic-sop-soc-ticket -Djansi.passthrough=true "-Dmaven.home=D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56.plugins\bean-invoker-intellij-plugin\lib\bean-invoker-agent-1.0.2-with-dependencies.jar" -Dspring.invokePort=6060 "-javaagent:D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\lib\idea_rt.jar=50645:D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-1\231.9011.4\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2023.1.2 --errors --update-snapshots -T 32 package
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56.plugins\bean-invoker-intellij-plugin\lib\bean-invoker-agent-1.0.2-with-dependencies.jar

Process finished with exit code 1

**Comment by newhoo** [comment]
temporary solution：
![image](https://github.com/newhoo/bean-invoker/assets/22903277/ac1bdeee-a827-4873-ba5f-64ad75e25b3f)

I will solve it later.

**Comment by newhoo** [comment]
升级`1.0.5`试试
