### ISSUE TITLE
有些项目无法使用

### ISSUE THREAD

**Issue by lians0** [newhoo/bean-invoker#4]
已经开启并重启项目，重启idea，依然无法使用。项目启动时也没有相关日志
插件对项目有什么要求吗？

**Comment by newhoo** [comment]
针对Spring应用有效。可以按以下检查一下
1. 是否为Spring应用，且包含这个类，执行该类时会将拦截：`org.springframework.context.support.AbstractApplicationContext`
2. 每个项目打开后会自动生成以下配置，
![image](https://github.com/newhoo/bean-invoker/assets/22903277/77f02582-346c-4958-b952-809548c73970)
3. 设置插件启用
![image](https://github.com/newhoo/bean-invoker/assets/22903277/a727db2e-2410-4632-8b15-e140c96620ad)
4. 启动项目，控制台查看信息。
![image](https://github.com/newhoo/bean-invoker/assets/22903277/470d4ef5-e764-4ac2-814e-c110a4b7a029)
