### ISSUE TITLE
多个项目同时启动时会有端口占用的情况

### ISSUE THREAD

**Issue by lians0** [newhoo/bean-invoker#6]
![image](https://github.com/newhoo/bean-invoker/assets/30581350/39130a53-c4ee-4a22-bc4c-c8d3eff1226a)
这里同时启动了3个项目，有一个报了端口占用。重启可以解决。
是不是判断端口占用的时机需要调整。

希望作者解决，加油

**Comment by newhoo** [comment]
点Run时会找一个未使用端口，初始端口都是6060，同时启动会出现以上问题。近期优化一下

**Comment by newhoo** [comment]
升级`1.0.6`试试
