### ISSUE TITLE
希望加入删除测试方法的功能

### ISSUE THREAD

**Issue by lians0** [newhoo/bean-invoker#8]
可以在这地方加个x号
![image](https://github.com/newhoo/bean-invoker/assets/30581350/ddc4e944-6f8f-4d29-99ff-824e7039aa9c)

有个窗口能查看所有生成的方法
统一删除

**Comment by newhoo** [comment]
目前没有精力实现，全局查找或者通过TODO插件查找测试方法蛮方便，通过手动删除吧。欢迎提PR实现
