### ISSUE TITLE
最新版快速生成无法设置快捷键了

### ISSUE THREAD

**Issue by lians0** [newhoo/bean-invoker#9]
![image](https://github.com/newhoo/bean-invoker/assets/30581350/13e1b91c-059f-4419-9ccb-2f19d1583a26)
之前的版本是可以设置快捷键的
![image](https://github.com/newhoo/bean-invoker/assets/30581350/0b8f14d7-38a2-4bc4-9e01-52d86013e872)

版本信息：
Bean Invoker：1.0.7
IDEA:
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023

祝好

**Comment by newhoo** [comment]
默认快捷键一直都有的 `option/alt x`。中文搜不到，搜下英文
![image](https://github.com/newhoo/bean-invoker/assets/22903277/cfc2f86a-62d2-438d-9a50-96e7fe34cee9)
